version: "3"

services:
  meow-api:
    build: ./meow_api
    env_file: .env
    environment:
      - DB_HOSTNAME=db
    ports:
      - "${LISTEN_PORT}:${LISTEN_PORT}"
    depends_on:
      - db

  db:
    image: mysql:8.0.42
    environment:
      MYSQL_ROOT_PASSWORD: rootpwd
      MYSQL_DATABASE: meow
      MYSQL_USER: meow
      MYSQL_PASSWORD: meow
    volumes:
      - ./seed.sql:/docker-entrypoint-initdb.d/seed.sql:ro
